export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>WorkoutShare</title>
        <meta name="theme-color" content="white" />
      </head>
      <body>{children}</body>
    </html>
  )
}
